openapi: 3.1.0
info:
  title: Modified Method Of CMLR
  version: 1.0.0

tags:
  - name: MLR
    description: Multivariate Linear Regression operations
  - name: Generator
    description: Generator operations

paths:
  /multivariate-linear-regression/modified-method-of-cmlr:
    post:
      summary: Constructs multivariate linear regression with modified method by Pavlov
      operationId: solveRegressionWithModifiedMethodOfCmlr
      tags:
        - MLR
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModifiedMethodOfCmlrRequestBody"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
                  format: double
                example: [1.0, 0, 3.0, 0, 6.0]
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestException"

  /random-numbers/int/matrix:
    post:
      summary: Generated random integer numbers in matrix
      operationId: getMatrixOfRandomIntNumbers
      tags:
        - Generator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IntRandomNumbersRequestBody"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: number
                    format: double
                example: [[1, 5], [3, 8]]
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestException"

  /random-numbers/double/matrix:
    post:
      summary: Generated random double numbers in matrix
      operationId: getMatrixOfRandomDoubleNumbers
      tags:
        - Generator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DoubleRandomNumbersRequestBody"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: number
                    format: double
                example: [[1.3, 5.1], [3.6, 8.4]]
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestException"

  /random-numbers/normal-distribution/matrix:
    post:
      summary: Generated normally distributed random double numbers in matrix
      operationId: getMatrixOfNormallyDistributedRandomNumbers
      tags:
        - Generator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatrixOfNormallyDistributedRandomNumbersRequestBody"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: number
                    format: double
                example: [
                  [1.300877568665368, 0.25905329568401003],
                  [-0.2740089312890524, -0.0412420225935336]
                ]
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestException"

components:
  schemas:
    ModifiedMethodOfCmlrRequestBody:
      type: object
      description: Request body for constructing multivariate linear regression based on correct coefficients
      required:
        - totalNumberOfExperimentsGroup
        - initialNumberOfExperimentsGroup
        - independentVariables
        - correctCoefficients
        - errors
      properties:
        totalNumberOfExperimentsGroup:
          type: integer
          minimum: 2
          description: Total number of experiments group
          example: 4
        initialNumberOfExperimentsGroup:
          type: integer
          minimum: 1
          description: Initial number of experiments group
          example: 2
        independentVariables:
          type: array
          items:
            type: array
            items:
              type: number
              format: double
            minItems: 1
          minItems: 1
          description: Independent variables matrix
          example: [
            [4, 1, 1, 1],
            [4, 4, 1, 1],
            [1, 4, 4, 1],
            [1, 1, 4, 4],
            [4, 4, 4, 1],
            [1, 4, 4, 4],
            [1, 1, 4, 4],
            [1, 1, 1, 4],
            [4, 4, 4, 4],
            [4, 1, 1, 1]
          ]
        correctCoefficients:
          type: array
          items:
            type: number
            format: double
          minItems: 1
          description: Correct coefficients array
          example: [1.0, 0, 3.0, 0, 6.0]
        errors:
          type: array
          items:
            type: array
            items:
              type: number
              format: double
            minItems: 1
          minItems: 1
          description: Errors matrix
          example: [
            [0.788541606954773, -0.329118400192516, -0.9942524568114388, 0.14453090647095862],
            [1.5777291605372172, -0.4155536133030628, 1.25506651745409, -0.40948223765297903],
            [0.8745405443882809, -0.8105631301182811, -1.5921658534929635, 0.9024856125194042],
            [0.4116676032206691, 0.234377371371492, 1.1014416865330987, 2.0368763885917343],
            [-0.8908512062255074, -0.5259277467960555, -0.5277014127423201, -0.13904531044831725],
            [0.45406959839855376, -0.16148876647353905, 0.8857088533554148, 0.6251851218899985],
            [-0.3519829765771218, -0.7699565203434863, -0.4134650554618632, -0.8256433525968532],
            [-0.2740089312890524, -0.0412420225935336, 0.5305536687668025, 0.252516459890898],
            [-0.40060766480268317, -0.17082774334393097, 1.4865967696768292, -1.2582772394256128],
            [1.300877568665368, 0.25905329568401003, 0.49757580456429407, 1.0750886072421677]
          ]

    BadRequestException:
      type: object
      description: Response for 400 HTTP status
      properties:
        globalErrors:
          type: array
          items:
            type: string
            example: Total number of experiments group should be greater than number of initial groups
          description: Errors based on multiple fields
        fieldErrors:
          type: array
          items:
            type: string
            example: Independent variables matrix is singular
          description: Errors based on specific field

    IntRange:
      type: object
      description: Range of integer numbers
      properties:
        start:
          type: integer
          description: Start of range inclusively
          example: 0
        end:
          type: integer
          description: End of range exclusively
          example: 10

    DoubleRange:
      type: object
      description: Range of double numbers
      properties:
        start:
          type: number
          format: double
          description: Start of range inclusively
          example: 0.5
        end:
          type: number
          format: double
          description: End of range exclusively
          example: 10.3

    IntRandomNumbersRequestBody:
      type: object
      description: Request body for generating matrix of random integer numbers
      properties:
        rows:
          type: integer
          minimum: 1
          description: Number of matrix rows
          example: 2
        columns:
          type: integer
          minimum: 1
          description: Number of matrix columns
          example: 2
        range:
          $ref: "#/components/schemas/IntRange"

    DoubleRandomNumbersRequestBody:
      type: object
      description: Request body for generating matrix of random double numbers
      properties:
        rows:
          type: integer
          minimum: 1
          description: Number of matrix rows
          example: 2
        columns:
          type: integer
          minimum: 1
          description: Number of matrix columns
          example: 2
        range:
          $ref: "#/components/schemas/DoubleRange"


    MatrixOfNormallyDistributedRandomNumbersRequestBody:
      type: object
      description: Request body for generating matrix of normally disctributed random double numbers
      properties:
        mean:
          type: number
          format: double
          description: Mathematical expectation
          example: 0
        stdDev:
          type: number
          format: double
          minimum: 0
          description: Standard deviation
          example: 1
        rows:
          type: integer
          minimum: 1
          description: Number of matrix rows
          example: 2
        columns:
          type: integer
          minimum: 1
          description: Number of matrix columns
          example: 2
